linter:
  rules:
    # Prevent code errors:
    - always_use_package_imports
    - avoid_slow_async_io
    - comment_references
    - no_wildcard_variable_uses
    - prefer_void_to_null
    - unawaited_futures

    # Code quality:
    - always_declare_return_types
    - type_annotate_public_apis
    - eol_at_end_of_file
    - package_api_docs

    # Style
    - avoid_escaping_inner_quotes

    - avoid_bool_literals_in_conditional_expressions
    - no_literal_bool_comparisons

    - directives_ordering
    - leading_newlines_in_multiline_strings
    - library_annotations # require library keyword after library annotation
    - matching_super_parameters # same ordering of positional super parameters
    - noop_primitive_operations
    - prefer_asserts_in_initializer_lists
    - prefer_expression_function_bodies
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_if_elements_to_conditional_expressions # new dart feature
    - prefer_mixin
    - prefer_single_quotes
    - sort_constructors_first
    - unnecessary_await_in_return
    - unnecessary_lambdas
    - unnecessary_null_aware_operator_on_extension_on_nullable
    - use_colored_box
    - use_decorated_box
    - use_if_null_to_convert_nulls_to_bools
    - use_to_and_as_if_applicable