name: inline_tab_view
description: "A TabBarView that can be nested in scrollables."
version: 1.0.0
repository: https://github.com/derdilla/inline_tab_view

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


# flutter:
