name: '⚙️ CI'
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  unit-tests:
    name: 'Testing 🧪'
    runs-on: ubuntu-slim
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 1.17.0
          cache: true
      - run: flutter config --no-analytics --suppress-analytics
      - name: Package tests
        run: flutter test
      - name: Example tests
        run: flutter test
        working-directory: example
  dart-lints:
    name: 'Linting 📝'
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 1.17.0
          cache: true
      - run: flutter config --no-analytics --suppress-analytics
      - name: "Package lints"
        run: flutter analyze
      - name: "Example lints"
        run: flutter analyze
        working-directory: example
  dart-format:
    if: false # FIXME: format behaves differently in CI
    name: "Formating ✅"
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 1.17.0
          cache: true
      - name: "Package format"
        run: dart format --output show --set-exit-if-changed .
      - name: "Example format"
        run: dart format --output show --set-exit-if-changed example